name: Deploy to Skynet
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.10.0'
        
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
      env:
        VUE_APP_GITHUB_SHA: ${{ github.sha }}
    
    - name: Deploy to Skynet
      uses: SkynetLabs/deploy-to-skynet-action@v2.0.2
      with:
        upload-dir: dist
        github-token: ${{ secrets.GITHUB_TOKEN }}
        registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}
        try-files:
          - index.html
          - /index.html
